_target_: tactile_learning.agents.rewarder.cosine.Cosine
expert_demos: ???
image_encoder: null 
tactile_encoder: null
device: ${device}
representation_types: ${reward_representations}
expert_frame_matches: ${expert_frame_matches}
episode_frame_matches: ${episode_frame_matches}