_target_: see_to_touch.agents.rewarder.euclidean.Euclidean
expert_demos: ???
image_encoder: null 
tactile_encoder: null
device: ${device}
representation_types: ${reward_representations}
expert_frame_matches: ${expert_frame_matches}
episode_frame_matches: ${episode_frame_matches}