name: see_to_touch
channels: 
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - pip
  - matplotlib
  - jupyter
  - jupyterlab
  - pytorch=1.12
  - torchvision=0.13
  - opencv=4.6
  - pyyaml=6.0
  - pytorch-lightning=1.7.7
  - einops=0.4.1
  - black
  - isort
  - pandas=1.5.1
  - seaborn=0.12.1
  - termcolor=2.1.0
  - timm=0.4.12
  - omegaconf
  - h5py
  - wandb
  - hydra-core
  - ipdb
  - pip:
    - ikpy
    - imageio
    - POT
    - scikit-image
    - scikit-learn
    - dm-env
    - info-nce-pytorch
    - gym