defaults:
  - deployer: vinn # This fails almost anywhere! 

visualize: false
loop: true
frequency: 4
deployment_dump_dir: null
data_representations: ['image','franka']
data_path: see_to_touch/tasks/<task-name> # User should fill this