defaults:
    - learner: bet
    - dataset: bet # tactile_tdex_dataset
    - optimizer: adam 

seed: 42
device: 1

learner_type: bet # Can be bet, image_byol, tactile_stacked_byol # tactile_stacked_byol tactile_linear_byol, bc, tactile_byol
self_supervised: false

# Demos to use 
demos_to_use: []

# Hyperparameters to be used everywhere
batch_size: 32
tactile_image_size: 64 # 224 # This could be changed for stacked or shared architectures
vision_image_size: 480
vision_view_num: 0
train_epochs: 1000
save_frequency: 10
train_dset_split: 0.95

distributed: false
num_workers: 4

# Data path to be set
object: mint_opening
experiment: ${learner_type}_${object}_view_${vision_view_num} # For now let's only train resnet
data_dir: /home/irmak/Workspace/Holo-Bot/extracted_data/${object}
checkpoint_dir: ??? # Will be set to hydra dir inside the code

# logger
logger: true # To init logger or not
log_frequency: 1

# hydra configuration - should be received separately
hydra:
    run:
        dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/${now:%Y.%m.%d}/${now:%H-%M}_${experiment}
