# @package suite
defaults:
  - _self_

suite: dexterousgym
name: 'dexterous_gym'
task_name: ${task.task_name} # Is received from the Cup Unstacking 

# task settings
frame_stack: 1
action_repeat: 1

save_snapshot: true
discount: 0.99
hidden_dim: 4068

# train settings
num_train_frames: 2010 
num_seed_frames: 200

task_make_fn:
  _target_: tactile_learning.environments.make
  name: ${suite.task_name}
  tactile_out_dir: ${tactile_out_dir}
  tactile_model_type: ${tactile_model_type}
  host_address: '172.24.71.240'
  camera_num: ${camera_num}
  height: 480
  width: 480
  tactile_dim: 1024 # This will be set by the train_online.make_agent code
  frame_stack: ${suite.frame_stack}
  action_repeat: ${suite.action_repeat}
  action_type: ${task.action_type} # fingertip/joint
  data_representations: ${data_representations} 