_target_: see_to_touch.agents.rl_learners.drqv2.DRQv2
action_shape: ??? # To be determined in the training code
repr_dim: ???
device: ${device}
actor: ${rl_learner.actor_cfg}
critic: ${rl_learner.critic_cfg}
critic_target: ${rl_learner.critic_cfg}
critic_target_tau: 0.01

stddev_schedule: 0.1
stddev_clip: 0.3
lr: 1e-4 
data_representations: ${data_representations}

separate_aug: False
name: drqv2

actor_cfg:
  _target_: see_to_touch.agents.rl_learners.drqv2.Actor
  action_shape: ${rl_learner.action_shape}
  repr_dim: ${rl_learner.repr_dim}
  hidden_dim: 64

critic_cfg:
  _target_: see_to_touch.agents.rl_learners.drqv2.Critic
  action_shape: ${rl_learner.action_shape}
  repr_dim: ${rl_learner.repr_dim}
  hidden_dim: 64
  feature_dim: 512