_target_: tactile_learning.deployers.BC
data_path: ??? # This is not used for this particular module though
deployment_dump_dir: deployment/dump/dir # User should change
out_dir: /bc/encoders/out/dir
view_num: 1