_target_: see_to_touch.deployers.BET
data_path: ??? 
deployment_dump_dir: ???
tactile_out_dir: null # TODO: Should add these model paths before running BET
image_out_dir: null
bet_model_out_dir: null

seq_length: 3
representation_types: ['image', 'tactile', 'kinova', 'allegro'] # Observations used in the representations
demos_to_use: []
view_num: 0