image_encoder:
  _target_: see_to_touch.models.ImageBCEncoder
  out_dim: 512
  in_channels: 3

tactile_encoder:
  _target_: see_to_touch.models.TactileBCEncoder
  in_channels: 3
  out_dim: 64

last_layer:
  _target_: see_to_touch.models.create_fc 
  input_dim: 512 
  output_dim: 23 # 16 + 7
  hidden_dims: [256, 64] 