image_out_dir: null # Input model weight here
image_model_type: temporal

vinn_image_out_dir: null
vinn_image_model_type: byol

data_path: /see_to_touch/tasks/eraser_turning

name: eraser_turning
task_name: CardTurning-v1
camera_num: 0

expert_demo_nums: [16]
arm_offset_scale_factor: 0.05
hand_offset_scale_factor: 0.25

offset_mask: [1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0]


action_type: robot