image_out_dir: null # Input the model weight here
image_model_type: temporal

vinn_image_out_dir: null
vinn_image_model_type: byol

data_path: /see_to_touch/tasks/mint_opening

name: mint_opening
task_name: MintOpening-v1
camera_num: 0

expert_demo_nums: [11]
arm_offset_scale_factor: 0.09
hand_offset_scale_factor: 0.1
offset_mask: [0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0]

action_type: robot