
image_out_dir: 
  - null
  - null 
  - null
image_model_type: temporal

data_path: 
  - /see_to_touch/tasks/tasks1 # Input task name
  - /see_to_touch/tasks/tasks2
  - /see_to_touch/tasks/tasks3

name: multi_task
task_name: MultiTask-v1
camera_num: 0

expert_demo_nums: 
  - [] # Should insert desired expert demo number here
  - []
  - []

arm_offset_scale_factor: # Should modify each of these separately
  - 0.07
  - 0.05
  - 0.06

hand_offset_scale_factor: 
  - 0.32
  - 0.25
  - 0.1

offset_mask: 
  - [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
  - [0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0]
  - [0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0]

action_type: robot