image_out_dir: null # Input the weight path here
image_model_type: temporal

vinn_image_out_dir: null
vinn_image_model_type: byol

data_path: /see_to_touch/tasks/peg_insertion

name: peg_insertion
task_name: PegInsertion-v1
camera_num: 0

expert_demo_nums: [4]
arm_offset_scale_factor: 0.05
hand_offset_scale_factor: 0.07

offset_mask: [1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] # peg insertion

action_type: robot