image_out_dir: null # Input the weight path here
image_model_type: temporal

vinn_image_out_dir: null
vinn_image_model_type: byol

data_path: /see_to_touch/tasks/plier_clipping

name: plier_clipping
task_name: PlierClipping-v1
camera_num: 0

expert_demo_nums: [40]
arm_offset_scale_factor: 0.05
hand_offset_scale_factor: 0.07

offset_mask: [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] # peg insertion

action_type: robot