# image_out_dir: /home/irmak/Workspace/tactile-learning/tactile_learning/out/2023.06.04/21-28_temporal_ssl_bs_32_epochs_1000_lr_1e-05_card_flipping_frame_diff_5_resnet
image_out_dir: null # Input the model weight path here
image_model_type: temporal

vinn_image_out_dir: 2023.06.07-17-45_image_byol_card_flipping_view_0_resnet
vinn_image_model_type: byol

data_path: /see_to_touch/tasks/sponge_flipping

name: sponge_flipping
task_name: CardFlipping-v1
camera_num: 0

expert_demo_nums: [24]
arm_offset_scale_factor: 0.08
hand_offset_scale_factor: 0.32 #sponge flipping
offset_mask: [1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] # sponge flipping

action_type: robot