image_out_dir: null # Input the model weight path here
image_model_type: temporal

vinn_image_out_dir: null
vinn_image_model_type: byol

data_path: /see_to_touch/tasks/sponge_flipping

name: sponge_flipping
task_name: CardFlipping-v1
camera_num: 0

expert_demo_nums: [24]
arm_offset_scale_factor: 0.08
hand_offset_scale_factor: 0.32 #sponge flipping
offset_mask: [1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0] # sponge flipping

action_type: robot