_target_: see_to_touch.datasets.TactileVisionActionDataset
data_path: ???
tactile_information_type: whole_hand #whole_hand, stacked - bc we use alexnet now
tactile_img_size: ${tactile_image_size}
vision_view_num: ${vision_view_num}
vision_img_size: ${vision_image_size}